### ISSUE TITLE
Error when running application after adding JcfModule to imports

### ISSUE THREAD

**Issue by richnz** [TrimAgency/angular-jcf-module#3]
I am getting the following error at runtime after I have added the JcfModule to the app.module.ts : 

> Could not find a declaration file for module 'jcf'. 'C:/Projects/Angular2Demo/Angular2Demo/node_modules/jcf/js/jcf.common.js' implicitly has an 'any' type.

I installed the module using npm and have added the module to the app.module file as below (this is a vanilla application just using the quickstart json) :

```
import { JcfModule } from 'angular2-jcf-directive/jcfModule/jcf.module';

import { AppComponent }  from './app.component';

@NgModule({
  imports:      [ BrowserModule, FormsModule, JcfModule ],
  declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ]
})'
```

As I am not using the CLI I have added the scripts as below to the index.html : 
```
<script src="js/jquery.js"></script>    
<script src="js/jcf.js"></script>
<script src="js/jcf.select.js"></script>
<script src="js/jcf.radio.js"></script>
<script src="js/jcf.checkbox.js"></script>
```

Is this an issue with the package or have I missed something in the setup?

**Comment by richnz** [comment]
I've tried the set up using CLI and this works perfectly so I'll use this going forwards. Not sure what I was doing wrong with the other method but I am fairly new to angular so maybe a rookie mistake somewhere.

One thing to note your readme needs a slight tweak for the .angular-cli-json file (replace :[ with a comma after "styles.css" ):
```
"styles": [
        "styles.css",
        "../node_modules/jcf/dist/css/theme-minimal/jcf.css"
      ],
```

Thanks for providing this module, really useful to be able to get up and running with this 👍

**Comment by dominiquemiller** [comment]
Thank you for your feedback! I have updated the Readme.md to reflect the typo.  Good catch!  I apologize for taking so long to respond to your requests.  

I am glad you were able to use the module and it was helpful!  

In response to your first comment, at first glance it looks like in your compiler options "noImplicitAny" is set to true. Since no type declaration files exist for the jcf plugin, you should exclude the jcf plugin from the compiler.  For example:
```
{
    "compilerOptions": {
        "noImplicitAny": true,
        "removeComments": true,
        "preserveConstEnums": true,
        "outFile": "../../built/local/tsc.js",
        "sourceMap": true
    },
    "include": [
        "src/**/*"
    ],
    "exclude": [
        // exclude jcf here
        "node_modules"
        "**/*.spec.ts"
    ]
}
``` 
That should hopefully remove the error you were experiencing.

If you encounter any additional issues or would like to expand the functionality of this module, please feel free to open a PR! 

Again sorry for taking so long to respond!
